---
- name: Deploy HTTPD Container
  hosts: all
  become: yes
  tasks:
    - name: Pull the latest image
      docker_image:
        name: my-httpd
        source: local

    - name: Stop and remove existing container
      docker_container:
        name: httpd_container
        state: absent

    - name: Run HTTPD container
      docker_container:
        name: httpd_container
        image: my-httpd
        state: started
        restart_policy: always
        published_ports:
          - "80:80"
