---
- name: Deploy HTTPD Container
  hosts: all
  become: yes
  tasks:
    - name: Pull the latest image
      docker_image:
        name: httpd
        source: local

    - name: Stop and remove existing container
      docker_container:
        name: suraj
        state: absent

    - name: Run HTTPD container
      docker_container:
        name: suraj
        image: httpd
        state: started
        restart_policy: always
        published_ports:
          - "80:80"
