- name: Deploy Docker Container
  hosts: all
  become: yes
  tasks:
    - name: Pull the Docker image
      docker_image:
        name: my-web-app
        source: pull
        tag: latest

    - name: Run the Docker container
      docker_container:
        name: my-web-app
        image: my-web-app:latest
        ports:
          - "80:80"
        state: started
